import type { FeatureDomain } from './types'

export const FEATURE_DOMAINS: FeatureDomain[] = [
  {
    id: 'auth',
    name: 'Authentication',
    description: 'Login, logout, session management, SSO, password reset',
    riskLevel: 'critical',
    icon: '🔐',
    filePatterns: [
      /src\/auth\//,
      /src\/components\/Auth/,
      /src\/components\/Login/,
      /src\/hooks\/useAuth/,
      /src\/context\/AuthContext/,
      /api\/auth\//,
      /middleware\/auth/,
      /src\/lib\/session/,
      /src\/pages\/(login|logout|signup)/,
      /src\/utils\/token/,
    ],
    smokeSpecs: [
      'e2e/auth/login.spec.ts',
      'e2e/auth/session.spec.ts',
    ],
    e2eSpecs: [
      'e2e/auth/login.spec.ts',
      'e2e/auth/logout.spec.ts',
      'e2e/auth/password-reset.spec.ts',
      'e2e/auth/sso.spec.ts',
      'e2e/auth/session.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 4, e2e: 22 },
  },
  {
    id: 'subscriptions',
    name: 'Subscriptions & Billing',
    description: 'Plans, upgrades, Stripe integration, invoices',
    riskLevel: 'critical',
    icon: '💳',
    filePatterns: [
      /src\/billing\//,
      /src\/subscriptions\//,
      /src\/payments\//,
      /src\/components\/Billing/,
      /src\/components\/Subscription/,
      /api\/billing\//,
      /api\/subscriptions\//,
      /api\/webhooks\/stripe/,
      /src\/lib\/stripe/,
      /src\/hooks\/useSubscription/,
    ],
    smokeSpecs: [
      'e2e/billing/subscribe.spec.ts',
      'e2e/billing/plan-display.spec.ts',
    ],
    e2eSpecs: [
      'e2e/billing/subscribe.spec.ts',
      'e2e/billing/upgrade.spec.ts',
      'e2e/billing/downgrade.spec.ts',
      'e2e/billing/invoices.spec.ts',
      'e2e/billing/plan-display.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 5, e2e: 28 },
  },
  {
    id: 'rbac',
    name: 'RBAC & Teams',
    description: 'Roles, permissions, team invites, org management',
    riskLevel: 'critical',
    icon: '👥',
    filePatterns: [
      /src\/rbac\//,
      /src\/teams\//,
      /src\/permissions\//,
      /src\/roles\//,
      /src\/components\/Team/,
      /src\/components\/Role/,
      /api\/teams\//,
      /api\/invites\//,
      /src\/hooks\/usePermissions/,
      /src\/middleware\/permissions/,
    ],
    smokeSpecs: [
      'e2e/rbac/role-enforcement.spec.ts',
      'e2e/teams/invite.spec.ts',
    ],
    e2eSpecs: [
      'e2e/rbac/admin.spec.ts',
      'e2e/rbac/viewer.spec.ts',
      'e2e/rbac/role-enforcement.spec.ts',
      'e2e/teams/invite.spec.ts',
      'e2e/teams/remove-member.spec.ts',
      'e2e/teams/org-management.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 6, e2e: 30 },
  },
  {
    id: 'viewer',
    name: 'Document Viewer',
    description: 'PDF/document rendering, annotations, zoom, page nav',
    riskLevel: 'high',
    icon: '📄',
    filePatterns: [
      /src\/viewer\//,
      /src\/components\/Viewer/,
      /src\/components\/Document/,
      /src\/components\/Annotation/,
      /src\/hooks\/useViewer/,
      /api\/documents\//,
      /src\/lib\/pdf/,
      /src\/workers\/renderer/,
    ],
    smokeSpecs: [
      'e2e/viewer/open-document.spec.ts',
    ],
    e2eSpecs: [
      'e2e/viewer/open-document.spec.ts',
      'e2e/viewer/annotations.spec.ts',
      'e2e/viewer/zoom-pan.spec.ts',
      'e2e/viewer/page-navigation.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 3, e2e: 16 },
  },
  {
    id: 'library',
    name: 'Library & Files',
    description: 'File management, folders, bulk actions, search within library',
    riskLevel: 'high',
    icon: '📁',
    filePatterns: [
      /src\/library\//,
      /src\/files\//,
      /src\/folders\//,
      /src\/components\/Library/,
      /src\/components\/FileList/,
      /src\/components\/Folder/,
      /api\/files\//,
      /api\/library\//,
      /src\/hooks\/useLibrary/,
    ],
    smokeSpecs: [
      'e2e/library/browse.spec.ts',
      'e2e/library/create-folder.spec.ts',
    ],
    e2eSpecs: [
      'e2e/library/browse.spec.ts',
      'e2e/library/create-folder.spec.ts',
      'e2e/library/rename.spec.ts',
      'e2e/library/move.spec.ts',
      'e2e/library/delete.spec.ts',
      'e2e/library/bulk-actions.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 4, e2e: 22 },
  },
  {
    id: 'explore',
    name: 'Explore & Search',
    description: 'Global search, filters, discovery, trending',
    riskLevel: 'medium',
    icon: '🔍',
    filePatterns: [
      /src\/explore\//,
      /src\/search\//,
      /src\/components\/Search/,
      /src\/components\/Explore/,
      /src\/hooks\/useSearch/,
      /api\/search\//,
      /api\/explore\//,
    ],
    smokeSpecs: [
      'e2e/explore/search.spec.ts',
    ],
    e2eSpecs: [
      'e2e/explore/search.spec.ts',
      'e2e/explore/filters.spec.ts',
      'e2e/explore/trending.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 2, e2e: 10 },
  },
  {
    id: 'navigation',
    name: 'Navigation & Routing',
    description: 'Sidebar, breadcrumbs, routing, deep links',
    riskLevel: 'medium',
    icon: '🧭',
    filePatterns: [
      /src\/components\/Sidebar/,
      /src\/components\/Nav/,
      /src\/components\/Breadcrumb/,
      /src\/router\//,
      /src\/routes\//,
      /src\/hooks\/useNavigation/,
      /src\/layouts\//,
    ],
    smokeSpecs: [
      'e2e/navigation/sidebar.spec.ts',
    ],
    e2eSpecs: [
      'e2e/navigation/sidebar.spec.ts',
      'e2e/navigation/routing.spec.ts',
      'e2e/navigation/breadcrumbs.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 2, e2e: 8 },
  },
  {
    id: 'onboarding',
    name: 'Onboarding',
    description: 'Signup flow, welcome wizard, first-run experience',
    riskLevel: 'high',
    icon: '🚀',
    filePatterns: [
      /src\/onboarding\//,
      /src\/components\/Onboarding/,
      /src\/components\/Welcome/,
      /src\/pages\/onboarding/,
      /api\/onboarding\//,
      /src\/hooks\/useOnboarding/,
    ],
    smokeSpecs: [
      'e2e/onboarding/signup-flow.spec.ts',
    ],
    e2eSpecs: [
      'e2e/onboarding/signup-flow.spec.ts',
      'e2e/onboarding/welcome-wizard.spec.ts',
      'e2e/onboarding/skip-steps.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 4, e2e: 14 },
  },
  {
    id: 'account',
    name: 'Account Settings',
    description: 'Profile, preferences, notifications, connected apps',
    riskLevel: 'medium',
    icon: '⚙️',
    filePatterns: [
      /src\/settings\//,
      /src\/account\//,
      /src\/profile\//,
      /src\/components\/Settings/,
      /src\/components\/Profile/,
      /api\/settings\//,
      /api\/account\//,
      /src\/hooks\/useSettings/,
    ],
    smokeSpecs: [
      'e2e/account/profile.spec.ts',
    ],
    e2eSpecs: [
      'e2e/account/profile.spec.ts',
      'e2e/account/notifications.spec.ts',
      'e2e/account/connected-apps.spec.ts',
      'e2e/account/delete-account.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 2, e2e: 12 },
  },
  {
    id: 'floor-plan',
    name: 'Floor Plan Editor',
    description: 'Drawing canvas, shapes, layers, export to image',
    riskLevel: 'high',
    icon: '🏗️',
    filePatterns: [
      /src\/floor-plan\//,
      /src\/editor\//,
      /src\/canvas\//,
      /src\/components\/FloorPlan/,
      /src\/components\/Canvas/,
      /src\/components\/Shape/,
      /src\/hooks\/useCanvas/,
      /src\/workers\/canvas/,
    ],
    smokeSpecs: [
      'e2e/floor-plan/open-editor.spec.ts',
      'e2e/floor-plan/draw-shape.spec.ts',
    ],
    e2eSpecs: [
      'e2e/floor-plan/open-editor.spec.ts',
      'e2e/floor-plan/draw-shape.spec.ts',
      'e2e/floor-plan/layers.spec.ts',
      'e2e/floor-plan/export.spec.ts',
      'e2e/floor-plan/undo-redo.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 5, e2e: 24 },
  },
  {
    id: 'artifacts',
    name: 'Artifacts & Exports',
    description: 'AI-generated content, export to PDF/Word/CSV',
    riskLevel: 'high',
    icon: '✨',
    filePatterns: [
      /src\/artifacts\//,
      /src\/exports\//,
      /src\/generators\//,
      /src\/components\/Artifact/,
      /src\/components\/Export/,
      /api\/artifacts\//,
      /api\/exports\//,
      /src\/lib\/export/,
    ],
    smokeSpecs: [
      'e2e/artifacts/generate.spec.ts',
      'e2e/artifacts/export-pdf.spec.ts',
    ],
    e2eSpecs: [
      'e2e/artifacts/generate.spec.ts',
      'e2e/artifacts/export-pdf.spec.ts',
      'e2e/artifacts/export-word.spec.ts',
      'e2e/artifacts/export-csv.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 4, e2e: 18 },
  },
  {
    id: 'uploads',
    name: 'Uploads & Downloads',
    description: 'File upload, download, drag-and-drop, chunked transfer',
    riskLevel: 'high',
    icon: '📤',
    filePatterns: [
      /src\/upload\//,
      /src\/download\//,
      /src\/components\/Upload/,
      /src\/components\/Dropzone/,
      /src\/hooks\/useUpload/,
      /api\/upload\//,
      /src\/lib\/chunked-upload/,
      /src\/workers\/upload/,
    ],
    smokeSpecs: [
      'e2e/uploads/upload-file.spec.ts',
      'e2e/uploads/download-file.spec.ts',
    ],
    e2eSpecs: [
      'e2e/uploads/upload-file.spec.ts',
      'e2e/uploads/upload-large.spec.ts',
      'e2e/uploads/drag-drop.spec.ts',
      'e2e/uploads/download-file.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 4, e2e: 18 },
  },
  {
    id: 'cross-cutting',
    name: 'Cross-cutting',
    description: 'Global config, feature flags, error boundaries, analytics',
    riskLevel: 'critical',
    icon: '⚡',
    filePatterns: [
      /src\/config\//,
      /src\/feature-flags\//,
      /src\/analytics\//,
      /src\/error-boundary/,
      /src\/providers\//,
      /src\/store\//,
      /src\/constants\//,
      /\.env/,
      /vite\.config/,
      /next\.config/,
    ],
    smokeSpecs: [
      'e2e/smoke/app-loads.spec.ts',
      'e2e/smoke/critical-path.spec.ts',
    ],
    e2eSpecs: [
      'e2e/smoke/app-loads.spec.ts',
      'e2e/smoke/critical-path.spec.ts',
      'e2e/smoke/feature-flags.spec.ts',
      'e2e/smoke/error-handling.spec.ts',
    ],
    avgRuntimeMinutes: { smoke: 4, e2e: 18 },
  },
]

export function matchDomains(filePath: string): FeatureDomain[] {
  return FEATURE_DOMAINS.filter(domain =>
    domain.filePatterns.some(pattern => pattern.test(filePath))
  )
}

export function getAllSmokeSpecs(): string[] {
  const all = FEATURE_DOMAINS.flatMap(d => d.smokeSpecs)
  return [...new Set(all)]
}

export function getAllE2eSpecs(): string[] {
  const all = FEATURE_DOMAINS.flatMap(d => d.e2eSpecs)
  return [...new Set(all)]
}
